//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCMAddrbook {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCCMAddrbook.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btClose {
            get {
                return ResourceManager.GetString("btClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string btConfirm {
            get {
                return ResourceManager.GetString("btConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btSave {
            get {
                return ResourceManager.GetString("btSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save window position.
        /// </summary>
        public static string cbSavePosition {
            get {
                return ResourceManager.GetString("cbSavePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save window size.
        /// </summary>
        public static string cbSaveSize {
            get {
                return ResourceManager.GetString("cbSaveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string gbConnection {
            get {
                return ResourceManager.GetString("gbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full info.
        /// </summary>
        public static string gbDetails {
            get {
                return ResourceManager.GetString("gbDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string gbWindow {
            get {
                return ResourceManager.GetString("gbWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCM Address Book.
        /// </summary>
        public static string lbAppTitle {
            get {
                return ResourceManager.GetString("lbAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Serhii Halushko, 2018.
        /// </summary>
        public static string lbCopyright {
            get {
                return ResourceManager.GetString("lbCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name: .
        /// </summary>
        public static string lbDomain {
            get {
                return ResourceManager.GetString("lbDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name: .
        /// </summary>
        public static string lbFriendlyName {
            get {
                return ResourceManager.GetString("lbFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name:.
        /// </summary>
        public static string lbGroupName {
            get {
                return ResourceManager.GetString("lbGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some icons from Yusuke Kamiyamane.
        /// </summary>
        public static string lbIconsInfo {
            get {
                return ResourceManager.GetString("lbIconsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address: .
        /// </summary>
        public static string lbIp {
            get {
                return ResourceManager.GetString("lbIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCM Viewer path: .
        /// </summary>
        public static string lbSCCMPath {
            get {
                return ResourceManager.GetString("lbSCCMPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.5.
        /// </summary>
        public static string lbVersion {
            get {
                return ResourceManager.GetString("lbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string mmEdit {
            get {
                return ResourceManager.GetString("mmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string mmFile {
            get {
                return ResourceManager.GetString("mmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _?.
        /// </summary>
        public static string mmHelp {
            get {
                return ResourceManager.GetString("mmHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string mmiAbout {
            get {
                return ResourceManager.GetString("mmiAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to PC.
        /// </summary>
        public static string mmiConnectPC {
            get {
                return ResourceManager.GetString("mmiConnectPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect via Remote Assistant.
        /// </summary>
        public static string mmiConnectRA {
            get {
                return ResourceManager.GetString("mmiConnectRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect via SCCM.
        /// </summary>
        public static string mmiConnectSccm {
            get {
                return ResourceManager.GetString("mmiConnectSccm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy domain name.
        /// </summary>
        public static string mmiCopyDomainName {
            get {
                return ResourceManager.GetString("mmiCopyDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy IP address.
        /// </summary>
        public static string mmiCopyIp {
            get {
                return ResourceManager.GetString("mmiCopyIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete node.
        /// </summary>
        public static string mmiDeleteNode {
            get {
                return ResourceManager.GetString("mmiDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string mmiExit {
            get {
                return ResourceManager.GetString("mmiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export address book....
        /// </summary>
        public static string mmiExportList {
            get {
                return ResourceManager.GetString("mmiExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Full info.
        /// </summary>
        public static string mmiFullInfo {
            get {
                return ResourceManager.GetString("mmiFullInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import address book....
        /// </summary>
        public static string mmiImportList {
            get {
                return ResourceManager.GetString("mmiImportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch _SCCM viewer.
        /// </summary>
        public static string mmiLaunchSCCM {
            get {
                return ResourceManager.GetString("mmiLaunchSCCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _group....
        /// </summary>
        public static string mmiNewGroup {
            get {
                return ResourceManager.GetString("mmiNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _node....
        /// </summary>
        public static string mmiNewPC {
            get {
                return ResourceManager.GetString("mmiNewPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options....
        /// </summary>
        public static string mmiOptions {
            get {
                return ResourceManager.GetString("mmiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string mmiProperties {
            get {
                return ResourceManager.GetString("mmiProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        public static string mmiRename {
            get {
                return ResourceManager.GetString("mmiRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Status bar.
        /// </summary>
        public static string mmiStatusBar {
            get {
                return ResourceManager.GetString("mmiStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ToolBar.
        /// </summary>
        public static string mmiToolBar {
            get {
                return ResourceManager.GetString("mmiToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string mmTools {
            get {
                return ResourceManager.GetString("mmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string mmView {
            get {
                return ResourceManager.GetString("mmView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select group for new node..
        /// </summary>
        public static string msgEmptySelection {
            get {
                return ResourceManager.GetString("msgEmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty selection.
        /// </summary>
        public static string msgEmptySelectionTitle {
            get {
                return ResourceManager.GetString("msgEmptySelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Assistance.
        /// </summary>
        public static string rbRemAssis {
            get {
                return ResourceManager.GetString("rbRemAssis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCM Viewer.
        /// </summary>
        public static string rbSCCM {
            get {
                return ResourceManager.GetString("rbSCCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: .
        /// </summary>
        public static string sbItems {
            get {
                return ResourceManager.GetString("sbItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last: .
        /// </summary>
        public static string sbLast {
            get {
                return ResourceManager.GetString("sbLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add node group.
        /// </summary>
        public static string tbtAddGroup {
            get {
                return ResourceManager.GetString("tbtAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add node.
        /// </summary>
        public static string tbtAddNode {
            get {
                return ResourceManager.GetString("tbtAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to remote PC.
        /// </summary>
        public static string tbtConnectTo {
            get {
                return ResourceManager.GetString("tbtConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit node.
        /// </summary>
        public static string tbtEditNode {
            get {
                return ResourceManager.GetString("tbtEditNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PC list.
        /// </summary>
        public static string tbtExportList {
            get {
                return ResourceManager.GetString("tbtExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import PC list.
        /// </summary>
        public static string tbtImportList {
            get {
                return ResourceManager.GetString("tbtImportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string tbtOptions {
            get {
                return ResourceManager.GetString("tbtOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string wtAbout {
            get {
                return ResourceManager.GetString("wtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group properties.
        /// </summary>
        public static string wtGroupProperties {
            get {
                return ResourceManager.GetString("wtGroupProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node properties.
        /// </summary>
        public static string wtNodeProperties {
            get {
                return ResourceManager.GetString("wtNodeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string wtOptions {
            get {
                return ResourceManager.GetString("wtOptions", resourceCulture);
            }
        }
    }
}
